# This rule is not used by the project clusterscan-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over scan.ahmali3.github.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterscan-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-admin-role
rules:
- apiGroups:
  - scan.ahmali3.github.io
  resources:
  - clusterscans
  verbs:
  - '*'
- apiGroups:
  - scan.ahmali3.github.io
  resources:
  - clusterscans/status
  verbs:
  - get
